# Generated by Django 3.0.3 on 2020-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
